# Copyright 2022 Canonical Ltd
# See LICENSE file for licensing details.

options:
  audit-log-retention-period-in-days:
    type: string
    description: |
      How long to hold audit logs for in days, i.e., 10 = 10 days.
      If the value 0 is used, the logs will never be purged.
      Logs are purged at 9AM UTC. Defaults to 0, which means by 
      default logs are never purged.
    default: "0"
  candid-agent-private-key:
    type: string
    description: |
      Private key of the agent user for accessing the candid API.
  candid-agent-public-key:
    type: string
    description: |
      Public key of the agent user for accessing the candid API.
  candid-agent-username:
    type: string
    description: |
      Name of the agent user for accessing the candid API.
  candid-url:
    type: string
    description: URL of candid server.
  candid-public-key:
    type: string
    description: Candid public key.
  controller-admins:
    type: string
    description: |
      Whitespace separated list of candid users (or groups) that are
      made controller admins by default.
  log-level:
    type: string
    description: |
      Level to out log messages at, one of "debug", "info", "warn",
      "error", "dpanic", "panic", and "fatal".
    default: info
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  uuid:
    type: string
    description: The UUID advertised by the JIMM controller.
  juju-dashboard-location:
    type: string
    default: https://jaas.ai/models
    description: URL of the Juju Dashboard for this controller.
  postgres-secret-storage:
    default: false
    type: boolean
    description: Enables the use of Postgres for secret storage if Vault is not related.
  public-key:
    type: string
    description: The public part of JIMM's macaroon bakery keypair.
  private-key:
    type: string
    description: The private part of JIMM's macaroon bakery keypair.
  dns-name:
    type: string
    description: DNS hostname that JIMM is being served from.
  vault-access-address:
    type: string
    description: |
      The source address for the connection to Vault. 
      This should be a single IP with no CIDR.
      E.g. 10.1.2.123
  jwt-expiry:
    type: string
    description: |
      Duration for the JWT expiry (defaults to 5 minutes).
      This is the JWT JIMM sends to a Juju controller to authenticate
      model related commands. Increase this if long running websocket
      connections are failing due to authentication errors.
    default: 5m
  session-expiry-duration:
    type: string
    default: 6h
    description: |
      Expiry duration for JIMM session tokens. These tokens are used
      by clients and their expiry determines how frequently a user
      must login.
  macaroon-expiry-duration:
    type: string
    default: 24h
    description: Expiry duration for authentication macaroons.
  secure-session-cookies:
    type: boolean
    default: true
    description: |
      Whether HTTPS must be enabled to set session cookies.
  session-cookie-max-age:
    type: int
    default: 86400
    description: |
      The max age for the session cookies, on subsequent logins, the session instance
      extended by this amount. 
  final-redirect-url:
    type: string
    default: "https://jimm.dashboard.com/auth/login/redirect"
    description: |
      The final redirect URL for JIMM to redirect to when completing a browser based
      login. This should be your dashboard.
