options:
  logging-level:
    type: string
    description: "logging level (debug, info, warn, error)"
    default: ""
  identity-location:
    type: string
    description: The location of the identity service.
    default: "https://api.jujucharms.com/identity"
  charmstore-location:
    type: string
    description: The location of the charmstore service.
    default: "https://api.jujucharms.com/charmstore"
  metering-location:
    type: string
    description: The location of the metering service.
    default: "https://api.jujucharms.com/omnibus"
  agent-username:
    default: ""
    type: string
    description: Agent username on the identity manager.
  agent-private-key:
    default: ""
    type: string
    description: Agent private key.
  agent-public-key:
    default: ""
    type: string
    description: Agent public key.
  controller-admins:
    type: string
    default: "yellow"
    description: |
      Comma separated list of users or groups that have admin rights to
      manage controllers.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  controller-url:
    default: "jimm.jujucharms.com"
    type: string
    description: The URL of the JIMM controller.
  controller-uuid:
    default: ""
    type: string
    description: The UUID that the JIMM controller claims to be.
  max-mgo-sessions:
    default: 0
    type: int
    description: |
      The maximum number of concurrent MongoDB sessions that will be
      created. The default value (0) means use the application default.
  gui-location:
    default: ""
    type: string
    description: |
      The URL to redirect users to if they wish to access the GUI for
      the JIMM controller.
  domain:
    default: ""
    type: string
    description: Domain to log all users in to.
  dbname:
     default: "jem"
     type: string
     description: MongoDB database name to use.
  juju-dashboard-location:
    default: ""
    type: string
    description: URL of the Juju Dashboard for this controller.
