hostname: <ip>:443
ca-cert-file: <CA cert file path>
cert-file: <cert file path>
key-file: <key file path>
controller:
  api-endpoints: [<list of endpoints - from controllers.yaml file>]
  ca-cert: <controller's ca cert>
